models/contact.py
from utils.db import db


class Contact(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(15))
    last_name = db.Column(db.String(15))
    email = db.Column(db.String(30))
    phone = db.Column(db.String(10))

    def __init__(self, name, last_name, email, phone):
        self.name = name
        self.last_name = last_name
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy
from config import path_connection

app = Flask(__name__)

app.secret_key = "secret key"
app.config["SQLALCHEMY_DATABASE_URI"] = path_connection
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

SQLAlchemy(app)
app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db

contacts = Blueprint('contact', __name__)
@contacts.route('/')
def home():
    contacts_actual = Contact.query.all()
    return render_template('index.html', contacts = contacts_actual)

@contacts.route('/new', methods=['POST'])
def add_contact():
    name = request.form['name']
    last_name = request.form['last_name']
    email = request.form['email']
    phone = request.form['phone']
    new_contact = Contact(name, last_name, email, phone)
    db.session.add(new_contact)
    db.session.commit()
    flash("Contacto añadido")
    return redirect(url_for('contact.home'))

@contacts.route('/delete/<id>')
def delete_contact(id):
    contact_delete = Contact.query.get(id)
    db.session.delete(contact_delete)
    db.session.commit()
    flash("Contacto eliminado")
    return redirect(url_for('contact.home'))

@contacts.route('/update/<id>', methods=['POST', 'GET'])
def update_contact(id):
    contact_update = Contact.query.get(id)
    if request.method == 'POST':
        contact_update.name = request.form['name']
        contact_update.last_name = request.form['last_name']
        contact_update.email = request.form['email']
        contact_update.phone = request.form['phone']
        db.session.commit()
        flash("Contacto actualizado")
        return redirect(url_for('contact.home'))
        
    return render_template('update.html', contact=contact_update)

@contacts.route('/about')
def about():
    return "Acerca de mi"

templates/index.html
{% extends 'layout.html' %}

{% block content %}
    
    <div class="row">
        <div class="col-md-5">
            {% include('partials/_message.html') %}
            {% include('partials/_form_contact.html') %}
        </div>
        
        <div class="col-md-7">
            {% for contact in contacts %}
                {% include('partials/_card_contact.html') %}
            {% endfor %}
        </div>
    </div>
    
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html data-theme="forest" lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD with Flask</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>    
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
</head>
<body>
    {% include('partials/_navbar.html') %}
    <div class="p-2">
        {% block content %}
        {% endblock%}
    </div>
</body>
</html>

templates/partials/_card_contact.html
<div class="card mb-1 text-white shadow" style="background-color: #031a3e;">
    <div class="card-body">
        <div class="d-flex justify-content-between">
            <h5>{{contact.name}}</h5>
            <div>
                <a href="{{ url_for('contact.update_contact', id=contact.id) }}" class="btn btn-dark btn-sm rounded-0">Actualizar</a>
                <a href="{{ url_for('contact.delete_contact', id=contact.id) }}" class="btn btn-danger btn-sm rounded-0">Eliminar</a>
            </div>
        </div>
        <p>{{contact.last_name}}</p>
        <p>{{contact.email}}</p>
        <p>{{contact.phone}}</p>
    </div>  
</div>

templates/partials/_form_contact.html
<form action="/new" method="POST" class="card bg-dark text-light needs-validation" novalidate>
    <div class="card-body p-4">
        <div class="mb-4">
            <label for="name" class="form-label">Nombre:</label>
                <input id="name" type="text" name="name" placeholder="Escribe el nombre..." class="form-control rounded-0
                bg-dark border-0 text-white" required> 

            <div class="invalid-feedback"> Escribe un nombre </div>
        </div>
        <div class="mb-4">
            <label for="last_name" class="form-label">Apellido:</label>
            <input id="last_name" type="text" name="last_name" placeholder="Escribe tu apellido..." class="form-control rounded-0
            bg-dark border-0 text-white" required>

            <div class="invalid-feedback"> Escribe un apellido </div>
        </div>
        <div class="mb-4">
            <label for="email" class="form-label">Email:</label>
            <input id="email" type="email" name="email" placeholder="Escribe tu correo..." class="form-control rounded-0
            bg-dark border-0 text-white" required>

            <div class="invalid-feedback"> Escribe un correo </div>
        </div>
        <div class="mb-4">
            <label for="phone" class="form-label">Celular:</label>
            <input id="phone" type="text" name="phone" placeholder="Escribe tu celular..." class="form-control rounded-0
            bg-dark border-0 text-white" required>
            <div class="invalid-feedback"> Escribe un número celular </div>
        </div>
        <button class="btn btn-secondary" type="submit">Guardar</button>
    </div>

    <script>
        (() => {
            'use strict'

            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            const forms = document.querySelectorAll('.needs-validation')

            // Loop over them and prevent submission
            Array.from(forms).forEach(form => {
                form.addEventListener('submit', event => {
                if (!form.checkValidity()) {
                    event.preventDefault()
                    event.stopPropagation()
                }

                form.classList.add('was-validated')
                }, false)
            })
        })()
    </script>
</form>

templates/partials/_message.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
    {% endif %}
{% endwith %}

templates/partials/_navbar.html
<nav class="navbar" style="background-color: #20d681;">
  <div class="container-fluid">
    <span class="navbar-brand h1 text-light">CRUD con Flask</span>
  </div>
</nav>

templates/update.html
{% extends 'layout.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <form action="/update/{{ contact.id }}" method="POST" class="card bg-dark text-white">
                <div class="card-body p-4">
                    <div class="mb-3">
                        <label for="name">Nombre:</label>
                            <input type="text" name="name" placeholder="Escribe el nombre..." value="{{contact.name}} "class="form-control rounded-0
                            bg-dark border-0 text-white"> 
                    </div>
                    <div class="mb-3">
                        <label for="last_name">Apellido:</label>
                        <input type="text" name="last_name" placeholder="Escribe tu apellido..." value="{{contact.last_name}}" class="form-control rounded-0
                        bg-dark border-0 text-white">
                    </div>
                    <div class="mb-3">
                        <label for="email">Email:</label>
                        <input type="email" name="email" placeholder="Escribe tu correo..." value="{{contact.email}}" class="form-control rounded-0
                        bg-dark border-0 text-white">
                    </div>
                    <div class="mb-3">
                        <label for="phone">Celular:</label>
                        <input type="text" name="phone" placeholder="Escribe tu celular..." value="{{contact.phone}}" class="form-control rounded-0
                        bg-dark border-0 text-white">
                    </div>
                    <button class="btn btn-secondary">Guardar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}